# Generated by Django 4.0.6 on 2022-08-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_adress_author_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='adress',
            new_name='address',
        ),
    ]
